In [1]:
import numpy as np
a = [1,2,3,4]
x1 = np.array(a)
x1

array([1, 2, 3, 4])

In [2]:
type(x1)

numpy.ndarray

In [3]:
x2 = np.arange(10)
x2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(x2)

numpy.ndarray

In [16]:
x3 = np.loadtxt('000001.csv', delimiter=',', skiprows=1,unpack=False,usecols=(1,4,6))
x3

array([[3.25863000e+03, 3.35052000e+03, 5.31352384e+10],
       [3.33080000e+03, 3.35145000e+03, 5.01661696e+10],
       [3.32665000e+03, 3.37395000e+03, 3.91918880e+10],
       [3.37196000e+03, 3.29346000e+03, 3.71131168e+10],
       [3.27697000e+03, 3.28541000e+03, 4.10240864e+10],
       [3.25821000e+03, 3.22932000e+03, 3.22064672e+10],
       [3.22354000e+03, 3.23530000e+03, 2.30725760e+10],
       [3.24234000e+03, 3.22244000e+03, 2.40190752e+10],
       [3.22407000e+03, 3.33646000e+03, 2.82546240e+10],
       [3.34360000e+03, 3.37650000e+03, 3.39876768e+10],
       [3.18973000e+03, 3.11635000e+03, 4.01098784e+10],
       [3.11456000e+03, 3.17305000e+03, 3.57080800e+10],
       [3.18909000e+03, 3.32361000e+03, 4.10956032e+10],
       [3.32732000e+03, 3.34334000e+03, 3.53382976e+10],
       [3.35710000e+03, 3.35176000e+03, 3.66249248e+10],
       [3.34726000e+03, 3.38318000e+03, 3.17540992e+10],
       [3.38985000e+03, 3.35296000e+03, 3.74517536e+10],
       [3.32572000e+03, 3.30574

In [17]:
x3.shape

(242, 3)

In [19]:
open,close,volume = np.loadtxt('000001.csv', delimiter=',', skiprows=1,unpack=True,usecols=(1,4,6))

In [21]:
close

array([3350.52, 3351.45, 3373.95, 3293.46, 3285.41, 3229.32, 3235.3 ,
       3222.44, 3336.46, 3376.5 , 3116.35, 3173.05, 3323.61, 3343.34,
       3351.76, 3383.18, 3352.96, 3305.74, 3262.3 , 3210.36, 3128.3 ,
       3204.91, 3174.13, 3136.53, 3075.91, 3095.12, 3141.59, 3157.7 ,
       3173.42, 3203.83, 3222.36, 3246.91, 3228.84, 3298.36, 3310.3 ,
       3336.28, 3263.05, 3279.53, 3248.48, 3241.19, 3302.41, 3286.07,
       3290.9 , 3349.32, 3372.91, 3449.3 , 3502.85, 3577.3 , 3582.27,
       3617.32, 3687.73, 3691.41, 3660.73, 3682.1 , 3691.1 , 3786.57,
       3747.9 , 3810.29, 3825.78, 3863.93, 3961.38, 3994.81, 3957.53,
       4034.31, 4121.71, 4135.56, 4084.16, 4194.82, 4287.3 , 4217.08,
       4293.62, 4398.49, 4414.51, 4393.69, 4527.4 , 4476.21, 4476.62,
       4441.65, 4480.46, 4298.71, 4229.27, 4112.21, 4205.92, 4333.58,
       4401.22, 4375.76, 4378.31, 4308.69, 4283.49, 4417.55, 4446.29,
       4529.42, 4657.6 , 4813.8 , 4910.9 , 4941.71, 4620.27, 4611.74,
       4828.74, 4910

In [22]:
y = np.arange(11)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
y+y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
y**y

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [25]:
y-y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
y/y

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [27]:
y*y

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [28]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
y[1::2]

array([1, 3, 5, 7, 9])

In [41]:
z = np.random.randint(1,100,10)
z

array([39, 68, 98, 21, 75, 49, 73, 52, 87, 72])

In [42]:
np.min(z)

21

In [43]:
np.max(z)

98

In [44]:
np.mean(z)

63.4

In [45]:
np.sort(z)

array([21, 39, 49, 52, 68, 72, 73, 75, 87, 98])

In [46]:
z.sort()

In [47]:
z.min()

21

In [48]:
z.max()

98

In [49]:
z.mean()

63.4

In [50]:
np.median(z)

70.0

In [51]:
z.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [52]:
np.variance(z)

AttributeError: module 'numpy' has no attribute 'variance'

In [53]:
z.variance()

AttributeError: 'numpy.ndarray' object has no attribute 'variance'

In [59]:
xx = np.random.randint(1,100,20)
xx

array([ 4, 99, 26, 23, 17, 31, 30, 55, 13, 65,  9, 39, 60, 54,  3, 71, 75,
       26, 83,  5])

In [58]:
# xx = np.random.randn(100) * 10

array([], shape=(0, 100), dtype=float64)

In [61]:
np.savetxt('000002.csv',xx)