In [5]:
# 1. 导入numpy库并简写为 np
import numpy as np

z = np.ones(10)
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [30]:
%time z = np.ones((1000,1000,1000))

Wall time: 3.04 s


In [32]:
%time z = np.zeros((1000,1000,1000))

Wall time: 96.8 ms


In [34]:
# 2. 打印numpy的版本和配置说明
np.__version__

'1.17.4'

In [36]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [37]:
# 3. 创建一个长度为10的空向量
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [38]:
# 4. 如何找到任何一个数组的内存大小？
print("数组z内存大小 %d bytes" % (z.size*z.itemsize))

数组z内存大小 80 bytes


In [39]:
# 5. 如何从命令行得到numpy中add函数的说明文档?
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x000001FECB0788C8>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

In [40]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

In [41]:
np.info(np.max)

 amax(*args, **kwargs)

Return the maximum of an array or maximum along an axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which to operate.  By default, flattened input is
    used.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, the maximum is selected over multiple axes,
    instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternative output array in which to place the result.  Must
    be of the same shape and buffer length as the expected output.
    See `doc.ufuncs` (Section "Output arguments") for more details.

keepdims : bool, optional
    If this is set to True, the axes which are reduced are left
    in the result as dimensions with size one. With this option,
    the result will broadcast correctly against the input array.

    If the default value is passed, then `keepdims` will not be
    passed through to the `amax` method of sub-classes of
    `n

In [42]:
# 6. 创建一个长度为10并且除了第五个值为1的空向量
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [43]:
# 7. 创建一个值域范围从10到49的向量
z = np.arange(10,49,1)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [44]:
# 8. 反转一个向量(第一个元素变为最后一个)
z_revert = z[::-1]
print("原向量：", z)
print("反转向量：", z_revert)

原向量： [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
反转向量： [48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [47]:
# 9. 创建一个 3x3 并且值从0到8的矩阵
# z = np.arange(0,9,1).reshape(3,3)
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [48]:
# 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引
z = [1,2,0,0,4,0]
non_z_index = np.nonzero(z)
print(non_z_index)

(array([0, 1, 4], dtype=int64),)


In [49]:
# 11. 创建一个 3x3 的单位矩阵
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
# 12. 创建一个 3x3x3的随机数组
z = np.random.random((3,3,3))
print(z)

[[[0.11397803 0.98755818 0.24486416]
  [0.99854575 0.80941248 0.06397908]
  [0.92166967 0.41080875 0.12344133]]

 [[0.59907118 0.82193621 0.80473698]
  [0.62891139 0.10430646 0.50805498]
  [0.18168804 0.23491599 0.10235937]]

 [[0.83901199 0.21991225 0.45371034]
  [0.10122146 0.11620187 0.36232952]
  [0.04521125 0.30345649 0.14145017]]]


In [54]:
# 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值
z = np.random.random((10,10))
print(z)
print("最大值：%s" % z.max())
print("最小值：%s" % z.min())

[[0.40614076 0.75179602 0.76346497 0.30365922 0.07521542 0.0468102
  0.78726705 0.31281139 0.34327579 0.71477416]
 [0.85138773 0.90326314 0.98062874 0.29072398 0.72998126 0.12802506
  0.98159226 0.79900622 0.2427276  0.48482832]
 [0.96358727 0.15517258 0.69155774 0.46945105 0.46195486 0.02993441
  0.599244   0.57091809 0.15966666 0.79616688]
 [0.28499605 0.15130408 0.02958405 0.27234539 0.37764915 0.37001862
  0.77315857 0.27917211 0.69127504 0.34622263]
 [0.67012119 0.94673035 0.67237783 0.94866238 0.8931639  0.17505559
  0.28164262 0.23768314 0.32175634 0.666754  ]
 [0.10923554 0.16066943 0.0237925  0.13672944 0.10250525 0.67917471
  0.45574131 0.98286967 0.16364186 0.97576884]
 [0.9168034  0.45321326 0.7584672  0.79941234 0.52802812 0.78161999
  0.70425085 0.28101869 0.99543131 0.57561234]
 [0.32149638 0.94213351 0.92968844 0.32603318 0.68781357 0.32346516
  0.88062295 0.87790058 0.94146483 0.49496766]
 [0.3471755  0.24004794 0.02711396 0.78997453 0.80677818 0.69091927
  0.41152215 

In [56]:
# 14. 创建一个长度为30的随机向量并找到它的平均值
z = np.random.random(30)
print(z)
print("平均值：", z.mean())

[0.2491504  0.1277372  0.48889105 0.83311394 0.09084235 0.65711198
 0.36950155 0.82495683 0.6444021  0.57478605 0.17117596 0.19676417
 0.26034361 0.71388528 0.08155767 0.13386948 0.17839217 0.82808214
 0.16906009 0.69944861 0.99845221 0.07198891 0.07253333 0.57732315
 0.06888984 0.86024306 0.70080043 0.4008491  0.92439058 0.45829297]
平均值： 0.4475612076834556


In [60]:
# 15.创建一二维数组，其中边界值为1，其余值为0
z = np.ones((8,8))
z[1:-1,1:-1] = 0

# z[1:-1,:] = 0
# z[:,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
