In [2]:
import numpy as np

# 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?
# 提示: np.seterr, np.errstate
defaults = np.seterr(all='ignore')

_ = np.seterr(**defaults)

z = np.ones(1)/0
print(z)

with np.errstate(divide='ignore'):
    z = np.ones(1)/0
    print(z)

[inf]
[inf]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


In [4]:
# 32. 下面的表达式是正确的吗?
# 提示: imaginary number
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
# 33. 如何得到昨天，今天，明天的日期?
# 提示: np.datetime64, np.timedelta64

today = np.datetime64('today', 'D')
print(today)

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2020-03-14
2020-03-13
2020-03-15


In [14]:
# 34. 如何得到所有与2016年7月对应的日期？
# 提示: np.arange(dtype=datetime64['D'])
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

z = np.arange('2020-02', '2020-03', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
['2020-02-01' '2020-02-02' '2020-02-03' '2020-02-04' '2020-02-05'
 '2020-02-06' '2020-02-07' '2020-02-08' '2020-02-09' '2020-02-10'
 '2020-02-11' '2020-02-12' '2020-02-13' '2020-02-14' '2020-02-15'
 '2020-02-16' '2020-02-17' '2020-02-18' '2020-02-19' '2020-02-20'
 '2020-02-21' '2020-02-22' '2020-02-23' '2020-02-24' '2020-02-25'
 '2020-02-26' '2020-02-27' '2020-02-28' '2020-02-29']


In [25]:
# 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3

np.add(A, B, out=B)
print(B)

np.divide(A, 2, out=A)
print(A)

np.negative(A, out=A)
print(A)

np.multiply(A, B, out=A)
print(A)

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


In [57]:
# 36. 用五种不同的方法去提取一个随机数组的整数部分
# 提示: %, np.floor, np.ceil, astype, np.trunc
# z = np.random.rand(10)
# z = np.random.random(10)
# z = np.random.randint(-10,10, 10)
# z = np.random.normal(10, 20, 10)
z = np.random.uniform(0, 10, 10)
# print(z)
# print(z%1)
# print(3%1, 2%1, 4.09%1)
print(z - z%1)

print(np.floor(z))

print(np.ceil(z) - 1)

print(z.astype(int))

print(np.trunc(z))

[2. 4. 7. 8. 1. 2. 4. 6. 2. 9.]
[2. 4. 7. 8. 1. 2. 4. 6. 2. 9.]
[2. 4. 7. 8. 1. 2. 4. 6. 2. 9.]
[2 4 7 8 1 2 4 6 2 9]
[2. 4. 7. 8. 1. 2. 4. 6. 2. 9.]


In [68]:
# 37. 创建一个5x5的矩阵，其中每行的数值范围从0到4
# z = np.ones((5, 5))
z = np.zeros((5, 5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [71]:
# 38. 通过考虑一个可生成10个整数的函数，来构建一个数组
# 提示: np.fromiter

def generate():
    for x in range(10):
        yield x

z = np.fromiter(generate(), dtype=float, count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [85]:
# 39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
# 提示: np.linspace
z = np.random.rand(10)
print(z)

# z = np.linspace(0, 1, 11, endpoint=False)
z = np.linspace(0, 1, 11, endpoint=False)[1:]
print(z)

[0.40496424 0.20039503 0.18043138 0.57351261 0.60176076 0.31951727
 0.84734866 0.67104948 0.52410357 0.30505853]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [91]:
# 40. 创建一个长度为10的随机向量，并将其排序
# z = np.sort(np.random.rand(100))
# z = np.sort(np.random.random(100))
# z = np.random.normal(0, 20, 100)
z = np.random.uniform(0, 20, 100)
z.sort()
print(z)

[ 0.37577339  0.7382079   0.75879248  0.95827278  1.63694442  1.85243683
  1.9427673   2.08167963  2.09891171  2.36736896  2.68706296  2.80532829
  2.84009352  2.99341088  3.13422226  3.23187267  3.32947802  3.76457957
  4.12272821  4.42646697  4.63197299  4.68205021  5.03443197  5.07365479
  5.11630489  5.20829918  5.2130287   5.25324806  5.69116963  6.0737246
  6.15940555  6.69144446  6.72345803  6.78956116  7.16297207  7.4224647
  7.63370913  7.82226771  7.90098772  8.04698     8.31856146  8.47323177
  8.48664539  8.54645101  8.73939625  8.82394786  8.92927912  9.1113285
  9.51766483 10.08524903 10.28293389 10.48044887 10.83692124 11.38858713
 11.44580074 11.57574364 11.63162631 11.79930481 11.98723527 12.11791732
 12.13221036 12.18013813 12.94510881 13.09030401 13.18456967 13.23252528
 13.43321099 13.49146125 13.50876953 13.96021667 13.978296   14.05045233
 14.19572654 14.31282166 14.52809384 14.57208992 14.64911852 15.10889946
 15.51394451 15.59377477 15.62948757 16.17317573 16.28

In [98]:
# 41.对于一个小数组，如何用比 np.sum更快的方式对其求和？
# 提示: np.add.reduce
z = np.random.random(10)
# print(z)
# %timeit s1 = np.sum(z)
# %timeit s2 = np.add.reduce(z)
s1 = np.sum(z)
s2 = np.add.reduce(z)
print(s1, s2)

5.59248564596768 5.59248564596768


In [103]:
# 42. 对于两个随机数组A和B，检查它们是否相等
# 提示: np.allclose, np.array_equal
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print(A == B)
equal = np.allclose(A, B)
print(equal)
equal = np.array_equal(A, B)
print(equal)

[ True  True  True  True  True]
True
True


In [106]:
# 43. 创建一个只读数组(read-only)
# 提示: flags.writeable
z = np.zeros(10)
z.flags.writeable = False
print(z)
# z[1] = 1

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [110]:
# 44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式
# hint: np.sqrt, np.arctan2
z = np.random.random((10, 2))
# print(z)
X, Y = z[:,0], z[:,1]
# print(X, Y)
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(R, T)

[1.18074959 1.03272904 0.72717031 0.0791748  0.95207447 0.16315444
 0.49535874 0.60401755 0.79956932 0.96269857] [0.97376896 1.08273094 0.52098013 1.17216252 1.55971216 0.98952863
 0.09478186 0.45746005 1.18879875 0.91058662]


In [127]:
# 45. 创建一个长度为10的向量，并将向量中最大值替换为1
# 提示: argmax
z = np.random.random(10)
# z[z.argmax()] = 0
z[z.argmax()] = 1
z[z.argmin()] = 10
z.sort()
print(z, z.max(), z.min())

[ 0.33966393  0.42861041  0.49971949  0.52507004  0.56516445  0.64378591
  0.66316859  0.66829812  1.         10.        ] 10.0 0.33966393420464214


In [131]:
# 46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域
# (提示: np.meshgrid)
z = np.zeros((5,5), [('x', float), ('y', float)])
# print(z)
z['x'],z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [133]:
# 47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
# 提示: np.subtract.outer
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(c)
print(np.linalg.det(c))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.163637117973


In [137]:
# 48. 打印每个numpy标量类型的最小值和最大值？
# 提示: np.iinfo, np.finfo, eps
for dtype in [np.int8,np.int32,np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    print('-' * 100)
print('+' * 100)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    print('-' * 100)

-128
127
----------------------------------------------------------------------------------------------------
-2147483648
2147483647
----------------------------------------------------------------------------------------------------
-9223372036854775808
9223372036854775807
----------------------------------------------------------------------------------------------------
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-3.4028235e+38
3.4028235e+38
1.1920929e-07
----------------------------------------------------------------------------------------------------
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
----------------------------------------------------------------------------------------------------


In [140]:
# 49. 如何打印一个数组中的所有数值?
# 提示: np.set_printoptions
# np.set_printoptions(threshold=np.nan)

z = np.zeros((16, 16))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
