In [2]:
import numpy as np

# 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?
# 提示: np.seterr, np.errstate
defaults = np.seterr(all='ignore')

_ = np.seterr(**defaults)

z = np.ones(1)/0
print(z)

with np.errstate(divide='ignore'):
    z = np.ones(1)/0
    print(z)

[inf]
[inf]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


In [4]:
# 32. 下面的表达式是正确的吗?
# 提示: imaginary number
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
# 33. 如何得到昨天，今天，明天的日期?
# 提示: np.datetime64, np.timedelta64

today = np.datetime64('today', 'D')
print(today)

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print(yesterday)

tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(tomorrow)

2020-03-14
2020-03-13
2020-03-15


In [14]:
# 34. 如何得到所有与2016年7月对应的日期？
# 提示: np.arange(dtype=datetime64['D'])
z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(z)

z = np.arange('2020-02', '2020-03', dtype='datetime64[D]')
print(z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']
['2020-02-01' '2020-02-02' '2020-02-03' '2020-02-04' '2020-02-05'
 '2020-02-06' '2020-02-07' '2020-02-08' '2020-02-09' '2020-02-10'
 '2020-02-11' '2020-02-12' '2020-02-13' '2020-02-14' '2020-02-15'
 '2020-02-16' '2020-02-17' '2020-02-18' '2020-02-19' '2020-02-20'
 '2020-02-21' '2020-02-22' '2020-02-23' '2020-02-24' '2020-02-25'
 '2020-02-26' '2020-02-27' '2020-02-28' '2020-02-29']


In [25]:
# 35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3

np.add(A, B, out=B)
print(B)

np.divide(A, 2, out=A)
print(A)

np.negative(A, out=A)
print(A)

np.multiply(A, B, out=A)
print(A)

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


In [27]:
# 36. 用五种不同的方法去提取一个随机数组的整数部分

