In [14]:
import numpy as np

# 16. 对于一个存在的数组，如何添加一个用0填充的边界？
z = np.ones((5,5))
z = np.pad(z, pad_width=1,mode='constant', constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
False


In [16]:
# 17. 以下表达式运行的结果分别式什么？
print(np.nan == np.nan)
print(0==np.nan)
print(np.inf==np.nan)
print(np.nan*np.nan)
print(np.nan - np.nan)
print(np.nan+np.nan)
print(np.nan>np.inf)
print(np.inf>np.nan)
print(0>np.nan)
print(np.nan>0)
print(np.inf>0,0>np.inf)
print(0*np.inf)
print(0.3==3*0.1)

False
False
False
nan
nan
nan
False
False
False
False
True False
nan
False


In [17]:
# 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置
# z = np.zeros((5,5))
z = np.diag(1+np.arange(4), k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
z = np.diag(1+np.arange(4), k=1)
print(z)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [20]:
z = np.diag(1+np.arange(4), k=4)
print(z)

[[0 0 0 0 1 0 0 0]
 [0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 4]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [23]:
# 19. 创建一个8x8 的矩阵，并且设置成棋盘样式
z = np.zeros((8,8), dtype=int)
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
# 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?
z = np.unravel_index(100,(6,7,8))
print(z)

(1, 5, 4)


In [25]:
# 21. 用tile函数去创建一个 8x8的棋盘样式矩阵
z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [26]:
z = np.tile(np.array([[0,1],[1,0]]), (5,5))
print(z)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [27]:
z = np.tile(np.array([[5,1],[1,5]]), (5,5))
print(z)

[[5 1 5 1 5 1 5 1 5 1]
 [1 5 1 5 1 5 1 5 1 5]
 [5 1 5 1 5 1 5 1 5 1]
 [1 5 1 5 1 5 1 5 1 5]
 [5 1 5 1 5 1 5 1 5 1]
 [1 5 1 5 1 5 1 5 1 5]
 [5 1 5 1 5 1 5 1 5 1]
 [1 5 1 5 1 5 1 5 1 5]
 [5 1 5 1 5 1 5 1 5 1]
 [1 5 1 5 1 5 1 5 1 5]]


In [30]:
# 22. 对一个5x5的随机矩阵做归一化
z = np.random.random((5, 5))
z =  z - z.min() / (z.max() - z.min())
print(z)

[[ 0.24092266  0.13474923  0.92588936  0.75559334  0.50896453]
 [ 0.33585892  0.02949227  0.05041705 -0.00506782  0.5865964 ]
 [ 0.24694906  0.89248711  0.27007491  0.74092921  0.70431345]
 [ 0.60359996  0.35865906  0.72897827  0.6497258  -0.00286894]
 [ 0.01158081  0.47948065  0.52379891  0.14856681  0.04739634]]


In [33]:
# 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？
color = np.dtype([
    ("r", np.ubyte, 1),
    ("g", np.ubyte, 1),
    ("b", np.ubyte, 1),
    ("a", np.ubyte, 1),
]);
print(color)


[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [34]:
# 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？
x = np.dot(np.ones((5,3)), np.ones((3,2)))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [41]:
# 25. 给定一个一维数组，对其在3到8之间的所有元素取反
z = np.arange(1, 11)
print(z)
z[(3 < z) & (z <= 8)] *= -1
print(z)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3 -4 -5 -6 -7 -8  9 10]


In [39]:
z = np.ones(10)
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [40]:
z[2:8] = 0
print(z)

[1. 1. 0. 0. 0. 0. 0. 0. 1. 1.]


In [42]:
# 26. 下面脚本运行后的结果是什么?
z = sum(range(5),-1)
print(z)

9


In [52]:
# 27. 考虑一个整数向量Z,下列表达合法的是哪个?
z = np.arange(5)
print(z*z)
print(z<z)
print(z>z)
print(2<<z>>2)
print(z<-z)
print(1j*z)
print(z/1/1)
print('+' * 30)
# 不合法
# print(z<z>z)

[ 0  1  4  9 16]
[False False False False False]
[False False False False False]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]
++++++++++++++++++++++++++++++


In [55]:
# 28. 下列表达式的结果分别是什么?
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [57]:
# 29. 如何从零位对浮点数组做舍入 ?
# 提示: np.uniform, np.copysign, np.ceil, np.abs
z = np.random.uniform(-10, +10, 10)
print(z)
print(np.copysign(np.ceil(np.abs(z)), z))

[ 1.26720388  6.62776533 -3.84903712 -5.2759722  -9.71620592  1.87868773
 -4.89789289  4.09959025  4.32456432  1.1673626 ]
[  2.   7.  -4.  -6. -10.   2.  -5.   5.   5.   2.]


In [59]:
# 30. 如何找到两个数组中的共同元素?
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)
print(z1)
print(z2)
print(np.intersect1d(z1, z2))

[1 1 0 8 1 2 0 6 8 7]
[7 7 1 3 4 3 6 4 8 4]
[1 6 7 8]
